# jbaruch-service properties
server:
  port: 8002

jbaruch:
  answers:
    - Омский мясокомбинат тоже хочет быть ведущий IT компанией в Омске
    - Омск лучший город в этой стране, ведь в нём есть Омский Мясокомбинат. К сожалению нет Netflix, но это мелочь.
    - Технологии идеальны, люди – ***аки ©
    - Всем артифактори ребятки!
    - Groovy рулит
    - Смотри Groovy Puzzlers
    - Смотри груви пазлеры
    - leftpad и npm говно
    - анпаблиш гейт говно
    - nexus это хороший телефон, всё
    - binary repository manager – artifactory
    - менеджер бинарных репозиториев – artifactory
    - самый лушчий бинарный репозиторий – artifactory
    - если думаете купить артифактори – не думайте, покупайте
    - думаю ли я о artifactory? Конечно думаю!
    - универсальная платформа для дистрибуции софта - Bintray
    - универсальная платформа для дистрибуции софта - Бинтрей
    - T-Shaped вуайеризм снова в моде
    - TShaped вуайеризм снова в моде
    - Рушь колодцы!
    - Мочи колодцы!

spring:
  main:
    allow-bean-definition-overriding: true
